name = "github-stars"
type = "webpack"
account_id = "a46f9a02578d51f3e8e135a14de082a0"
workers_dev = true
zone_id = ""
webpack_config = "webpack.config.js"

[env.staging]
name = "github-star-counter-staging"

[env.production]
name = "github-star-counter"
